import { MutualFund } from './mutualfunds.types';

export const MOCK_MUTUAL_FUNDS: MutualFund[] = [
  // ==========================================
  // LARGE CAP FUNDS
  // ==========================================
  {
    id: 'hdfc-top-100',
    name: 'HDFC Top 100 Fund',
    amc: 'HDFC Mutual Fund',
    amcCode: 'HDFC',
    category: 'large',
    categoryLabel: 'Large Cap Fund',
    planType: 'Direct Plan - Growth',
    rating: 5,
    riskLevel: 'Very High',
    benchmark: 'NIFTY 100 TRI',
    currentNav: 1042.85,
    navChange: 8.45,
    navChangePct: 0.82,
    navDate: '21 Sep 2026',
    returns1M: 2.1,
    returns6M: 9.4,
    returns1Y: 22.8,
    returns3Y: 19.4,
    returns5Y: 17.6,
    returnsInception: 14.8,
    expenseRatio: 0.89,
    regularExpenseRatio: 1.72,
    aumCrores: 34820,
    minSipAmount: 500,
    minLumpsumAmount: 1000,
    exitLoad: '1.0% if redeemed within 365 days; Nil thereafter',
    lockInPeriod: 'None',
    turnoverRatioPct: 18.5,
    sharpeRatio: 1.15,
    beta: 0.94,
    manager: {
      name: 'Rahul Baijal',
      experienceYears: 22,
      tenureWithFund: '3.8 Years',
      education: 'B.E, PGDM (IIM Calcutta)',
    },
    aiRecommendation: {
      isRecommended: true,
      matchScore: 96,
      badgeText: 'Top Large Cap Alpha',
      rationale: 'Outstanding risk-adjusted track record over 3 and 5-year horizons with lower downside volatility than peers.',
      pros: [
        'Consistently beat category average by +2.8% annually over 5 years',
        'High liquidity with ₹34,800+ Cr AUM in India’s leading bluechips',
        'Strong downside protection in correction phases',
      ],
      cons: [
        'Slightly higher direct expense ratio (0.89%) compared to category minimum',
        'Concentrated banking & financial services exposure (34%)',
      ],
    },
    topHoldings: [
      { id: 'h1', name: 'HDFC Bank Ltd.', sector: 'Financial Services', allocationPct: 9.8, symbol: 'HDFCBANK' },
      { id: 'h2', name: 'ICICI Bank Ltd.', sector: 'Financial Services', allocationPct: 8.9, symbol: 'ICICIBANK' },
      { id: 'h3', name: 'Reliance Industries Ltd.', sector: 'Energy & Oil', allocationPct: 8.2, symbol: 'RELIANCE' },
      { id: 'h4', name: 'Infosys Ltd.', sector: 'Information Technology', allocationPct: 6.4, symbol: 'INFY' },
      { id: 'h5', name: 'Larsen & Toubro Ltd.', sector: 'Construction', allocationPct: 5.1, symbol: 'LT' },
      { id: 'h6', name: 'Tata Consultancy Services', sector: 'Information Technology', allocationPct: 4.8, symbol: 'TCS' },
      { id: 'h7', name: 'ITC Ltd.', sector: 'Consumer FMCG', allocationPct: 4.2, symbol: 'ITC' },
      { id: 'h8', name: 'Bharti Airtel Ltd.', sector: 'Telecommunication', allocationPct: 3.9, symbol: 'BHARTIARTL' },
      { id: 'h9', name: 'State Bank of India', sector: 'Financial Services', allocationPct: 3.4, symbol: 'SBIN' },
      { id: 'h10', name: 'Axis Bank Ltd.', sector: 'Financial Services', allocationPct: 3.1, symbol: 'AXISBANK' },
    ],
    sectorAllocations: [
      { sector: 'Financial Services', allocationPct: 34.2, color: '#3B82F6' },
      { sector: 'Information Technology', allocationPct: 15.6, color: '#8B5CF6' },
      { sector: 'Energy & Petrochemicals', allocationPct: 11.4, color: '#F59E0B' },
      { sector: 'Consumer Goods & FMCG', allocationPct: 9.8, color: '#10B981' },
      { sector: 'Capital Goods & Infra', allocationPct: 8.5, color: '#EC4899' },
      { sector: 'Automobile', allocationPct: 7.2, color: '#6366F1' },
      { sector: 'Cash & Short Instruments', allocationPct: 13.3, color: '#94A3B8' },
    ],
    returnsComparison: [
      { period: '1M', fundReturn: 2.1, categoryAvg: 1.6, benchmarkReturn: 1.8 },
      { period: '6M', fundReturn: 9.4, categoryAvg: 8.1, benchmarkReturn: 8.7 },
      { period: '1Y', fundReturn: 22.8, categoryAvg: 19.5, benchmarkReturn: 20.4 },
      { period: '3Y', fundReturn: 19.4, categoryAvg: 16.8, benchmarkReturn: 17.2 },
      { period: '5Y', fundReturn: 17.6, categoryAvg: 15.1, benchmarkReturn: 15.8 },
      { period: 'Inception', fundReturn: 14.8, categoryAvg: 12.9, benchmarkReturn: 13.2 },
    ],
    navHistory: {
      '1M': [
        { date: '21 Aug', value: 1021.4 },
        { date: '28 Aug', value: 1026.8 },
        { date: '04 Sep', value: 1024.1 },
        { date: '11 Sep', value: 1035.7 },
        { date: '18 Sep', value: 1039.2 },
        { date: '21 Sep', value: 1042.85 },
      ],
      '6M': [
        { date: 'Mar 26', value: 953.2 },
        { date: 'Apr 26', value: 978.4 },
        { date: 'May 26', value: 962.1 },
        { date: 'Jun 26', value: 998.6 },
        { date: 'Jul 26', value: 1018.3 },
        { date: 'Aug 26', value: 1029.0 },
        { date: 'Sep 26', value: 1042.85 },
      ],
      '1Y': [
        { date: 'Sep 25', value: 849.2 },
        { date: 'Nov 25', value: 884.0 },
        { date: 'Jan 26', value: 918.5 },
        { date: 'Mar 26', value: 953.2 },
        { date: 'May 26', value: 962.1 },
        { date: 'Jul 26', value: 1018.3 },
        { date: 'Sep 26', value: 1042.85 },
      ],
      '3Y': [
        { date: '2023', value: 612.4 },
        { date: '2024', value: 728.6 },
        { date: '2025', value: 874.1 },
        { date: '2026', value: 1042.85 },
      ],
      '5Y': [
        { date: '2021', value: 463.5 },
        { date: '2022', value: 521.8 },
        { date: '2023', value: 612.4 },
        { date: '2024', value: 728.6 },
        { date: '2025', value: 874.1 },
        { date: '2026', value: 1042.85 },
      ],
      'ALL': [
        { date: '2016', value: 245.0 },
        { date: '2018', value: 334.2 },
        { date: '2020', value: 398.0 },
        { date: '2022', value: 521.8 },
        { date: '2024', value: 728.6 },
        { date: '2026', value: 1042.85 },
      ],
    },
  },
  {
    id: 'mirae-asset-large-cap',
    name: 'Mirae Asset Large Cap Fund',
    amc: 'Mirae Asset Mutual Fund',
    amcCode: 'MIRAE',
    category: 'large',
    categoryLabel: 'Large Cap Fund',
    planType: 'Direct Plan - Growth',
    rating: 4,
    riskLevel: 'Very High',
    benchmark: 'NIFTY 100 TRI',
    currentNav: 118.42,
    navChange: 0.64,
    navChangePct: 0.54,
    navDate: '21 Sep 2026',
    returns1M: 1.8,
    returns6M: 8.6,
    returns1Y: 20.4,
    returns3Y: 17.8,
    returns5Y: 16.5,
    returnsInception: 16.2,
    expenseRatio: 0.54,
    regularExpenseRatio: 1.58,
    aumCrores: 41200,
    minSipAmount: 500,
    minLumpsumAmount: 5000,
    exitLoad: '1.0% if redeemed within 365 days; Nil thereafter',
    lockInPeriod: 'None',
    turnoverRatioPct: 22.0,
    sharpeRatio: 1.08,
    beta: 0.98,
    manager: {
      name: 'Gaurav Khandelwal',
      experienceYears: 18,
      tenureWithFund: '5.2 Years',
      education: 'Chartered Accountant, CFA',
    },
    aiRecommendation: {
      isRecommended: true,
      matchScore: 92,
      badgeText: 'Low Expense Pioneer',
      rationale: 'One of the lowest direct expense ratios in the category (0.54%) coupled with diversified mega-cap portfolio.',
      pros: [
        'Ultra-low expense ratio saves up to 1% compounded over 10 years',
        'High portfolio diversification across 60+ blue chips',
      ],
      cons: [
        'Large AUM size can limit agile sector rotation',
      ],
    },
    topHoldings: [
      { id: 'm1', name: 'ICICI Bank Ltd.', sector: 'Financial Services', allocationPct: 9.4, symbol: 'ICICIBANK' },
      { id: 'm2', name: 'HDFC Bank Ltd.', sector: 'Financial Services', allocationPct: 9.1, symbol: 'HDFCBANK' },
      { id: 'm3', name: 'Reliance Industries Ltd.', sector: 'Energy & Oil', allocationPct: 8.6, symbol: 'RELIANCE' },
      { id: 'm4', name: 'Infosys Ltd.', sector: 'Information Technology', allocationPct: 5.9, symbol: 'INFY' },
      { id: 'm5', name: 'Bharti Airtel Ltd.', sector: 'Telecommunication', allocationPct: 4.8, symbol: 'BHARTIARTL' },
    ],
    sectorAllocations: [
      { sector: 'Financial Services', allocationPct: 32.8, color: '#3B82F6' },
      { sector: 'Information Technology', allocationPct: 14.9, color: '#8B5CF6' },
      { sector: 'Energy & Oil', allocationPct: 12.1, color: '#F59E0B' },
      { sector: 'Consumer Discretionary', allocationPct: 10.5, color: '#10B981' },
      { sector: 'Automotive', allocationPct: 8.1, color: '#EC4899' },
      { sector: 'Others / Cash', allocationPct: 21.6, color: '#94A3B8' },
    ],
    returnsComparison: [
      { period: '1M', fundReturn: 1.8, categoryAvg: 1.6, benchmarkReturn: 1.8 },
      { period: '6M', fundReturn: 8.6, categoryAvg: 8.1, benchmarkReturn: 8.7 },
      { period: '1Y', fundReturn: 20.4, categoryAvg: 19.5, benchmarkReturn: 20.4 },
      { period: '3Y', fundReturn: 17.8, categoryAvg: 16.8, benchmarkReturn: 17.2 },
      { period: '5Y', fundReturn: 16.5, categoryAvg: 15.1, benchmarkReturn: 15.8 },
      { period: 'Inception', fundReturn: 16.2, categoryAvg: 12.9, benchmarkReturn: 13.2 },
    ],
    navHistory: {
      '1M': [
        { date: '21 Aug', value: 116.3 },
        { date: '28 Aug', value: 116.9 },
        { date: '04 Sep', value: 116.5 },
        { date: '11 Sep', value: 117.6 },
        { date: '18 Sep', value: 118.1 },
        { date: '21 Sep', value: 118.42 },
      ],
      '6M': [
        { date: 'Mar 26', value: 109.1 },
        { date: 'Apr 26', value: 111.4 },
        { date: 'May 26', value: 110.2 },
        { date: 'Jun 26', value: 114.0 },
        { date: 'Jul 26', value: 116.2 },
        { date: 'Aug 26', value: 117.0 },
        { date: 'Sep 26', value: 118.42 },
      ],
      '1Y': [
        { date: 'Sep 25', value: 98.3 },
        { date: 'Nov 25', value: 102.1 },
        { date: 'Jan 26', value: 105.8 },
        { date: 'Mar 26', value: 109.1 },
        { date: 'May 26', value: 110.2 },
        { date: 'Jul 26', value: 116.2 },
        { date: 'Sep 26', value: 118.42 },
      ],
      '3Y': [
        { date: '2023', value: 72.5 },
        { date: '2024', value: 85.1 },
        { date: '2025', value: 100.8 },
        { date: '2026', value: 118.42 },
      ],
      '5Y': [
        { date: '2021', value: 55.2 },
        { date: '2022', value: 63.4 },
        { date: '2023', value: 72.5 },
        { date: '2024', value: 85.1 },
        { date: '2025', value: 100.8 },
        { date: '2026', value: 118.42 },
      ],
      'ALL': [
        { date: '2016', value: 31.2 },
        { date: '2018', value: 42.6 },
        { date: '2020', value: 48.9 },
        { date: '2022', value: 63.4 },
        { date: '2024', value: 85.1 },
        { date: '2026', value: 118.42 },
      ],
    },
  },
  {
    id: 'icici-pru-bluechip',
    name: 'ICICI Prudential Bluechip Fund',
    amc: 'ICICI Prudential Mutual Fund',
    amcCode: 'ICICI',
    category: 'large',
    categoryLabel: 'Large Cap Fund',
    planType: 'Direct Plan - Growth',
    rating: 5,
    riskLevel: 'Very High',
    benchmark: 'NIFTY 100 TRI',
    currentNav: 108.76,
    navChange: 0.92,
    navChangePct: 0.85,
    navDate: '21 Sep 2026',
    returns1M: 2.3,
    returns6M: 10.2,
    returns1Y: 23.4,
    returns3Y: 18.9,
    returns5Y: 17.2,
    returnsInception: 15.6,
    expenseRatio: 0.91,
    regularExpenseRatio: 1.68,
    aumCrores: 56900,
    minSipAmount: 100,
    minLumpsumAmount: 1000,
    exitLoad: '1.0% within 365 days; Nil after',
    lockInPeriod: 'None',
    turnoverRatioPct: 15.0,
    sharpeRatio: 1.18,
    beta: 0.91,
    manager: {
      name: 'Anish Tawakley',
      experienceYears: 25,
      tenureWithFund: '6.5 Years',
      education: 'B.Tech (IIT Delhi), PGDM (IIM Bangalore)',
    },
    aiRecommendation: {
      isRecommended: true,
      matchScore: 94,
      badgeText: 'Low Volatility Leader',
      rationale: 'Lowest portfolio volatility in large-cap peer set with ₹100 micro-SIP entry.',
      pros: [
        'Super low barrier to entry: start with just ₹100/month SIP',
        'Strong capital preservation during bear markets',
      ],
      cons: [
        'Slightly conservative posture may lag in fast momentum bull rallies',
      ],
    },
    topHoldings: [
      { id: 'i1', name: 'ICICI Bank Ltd.', sector: 'Financial Services', allocationPct: 10.1, symbol: 'ICICIBANK' },
      { id: 'i2', name: 'Reliance Industries Ltd.', sector: 'Energy', allocationPct: 9.3, symbol: 'RELIANCE' },
      { id: 'i3', name: 'Infosys Ltd.', sector: 'Technology', allocationPct: 7.8, symbol: 'INFY' },
      { id: 'i4', name: 'Larsen & Toubro Ltd.', sector: 'Infrastructure', allocationPct: 6.2, symbol: 'LT' },
    ],
    sectorAllocations: [
      { sector: 'Financial Services', allocationPct: 35.1, color: '#3B82F6' },
      { sector: 'Information Technology', allocationPct: 16.4, color: '#8B5CF6' },
      { sector: 'Energy & Oil', allocationPct: 11.2, color: '#F59E0B' },
      { sector: 'Automobile', allocationPct: 8.5, color: '#10B981' },
      { sector: 'Others & Cash', allocationPct: 28.8, color: '#94A3B8' },
    ],
    returnsComparison: [
      { period: '1M', fundReturn: 2.3, categoryAvg: 1.6, benchmarkReturn: 1.8 },
      { period: '6M', fundReturn: 10.2, categoryAvg: 8.1, benchmarkReturn: 8.7 },
      { period: '1Y', fundReturn: 23.4, categoryAvg: 19.5, benchmarkReturn: 20.4 },
      { period: '3Y', fundReturn: 18.9, categoryAvg: 16.8, benchmarkReturn: 17.2 },
      { period: '5Y', fundReturn: 17.2, categoryAvg: 15.1, benchmarkReturn: 15.8 },
      { period: 'Inception', fundReturn: 15.6, categoryAvg: 12.9, benchmarkReturn: 13.2 },
    ],
    navHistory: {
      '1M': [{ date: '21 Aug', value: 106.3 }, { date: '21 Sep', value: 108.76 }],
      '6M': [{ date: 'Mar 26', value: 98.7 }, { date: 'Sep 26', value: 108.76 }],
      '1Y': [{ date: 'Sep 25', value: 88.1 }, { date: 'Sep 26', value: 108.76 }],
      '3Y': [{ date: '2023', value: 64.7 }, { date: '2026', value: 108.76 }],
      '5Y': [{ date: '2021', value: 49.2 }, { date: '2026', value: 108.76 }],
      'ALL': [{ date: '2016', value: 28.4 }, { date: '2026', value: 108.76 }],
    },
  },

  // ==========================================
  // MID CAP FUNDS
  // ==========================================
  {
    id: 'hdfc-mid-cap-opportunities',
    name: 'HDFC Mid-Cap Opportunities Fund',
    amc: 'HDFC Mutual Fund',
    amcCode: 'HDFC',
    category: 'mid',
    categoryLabel: 'Mid Cap Fund',
    planType: 'Direct Plan - Growth',
    rating: 5,
    riskLevel: 'Very High',
    benchmark: 'NIFTY Midcap 150 TRI',
    currentNav: 182.35,
    navChange: 2.15,
    navChangePct: 1.19,
    navDate: '21 Sep 2026',
    returns1M: 3.4,
    returns6M: 14.8,
    returns1Y: 34.2,
    returns3Y: 26.5,
    returns5Y: 23.8,
    returnsInception: 19.4,
    expenseRatio: 0.76,
    regularExpenseRatio: 1.62,
    aumCrores: 68450,
    minSipAmount: 500,
    minLumpsumAmount: 1000,
    exitLoad: '1.0% within 365 days; Nil after',
    lockInPeriod: 'None',
    turnoverRatioPct: 29.4,
    sharpeRatio: 1.42,
    beta: 0.88,
    manager: {
      name: 'Chirag Setalvad',
      experienceYears: 26,
      tenureWithFund: '14.2 Years',
      education: 'B.S. in Computer Science (North Carolina), MBA',
    },
    aiRecommendation: {
      isRecommended: true,
      matchScore: 98,
      badgeText: 'Mid Cap Flagship ⚡',
      rationale: 'Exceptional 14+ year manager tenure with top-quartile alpha generation across 3 bull & bear cycles.',
      pros: [
        'Legendary track record: 23.8% CAGR over 5 years vs 19.2% benchmark',
        'Extensive mid-cap stock research and high conviction ideas',
        'Remarkable downside protection during sharp corrections',
      ],
      cons: [
        'High AUM (₹68,400+ Cr) requires investing in upper-band mid caps',
      ],
    },
    topHoldings: [
      { id: 'hm1', name: 'Indian Hotels Co. Ltd.', sector: 'Consumer Services', allocationPct: 4.8, symbol: 'INDHOTEL' },
      { id: 'hm2', name: 'Max Healthcare Institute', sector: 'Healthcare', allocationPct: 4.3, symbol: 'MAXHEALTH' },
      { id: 'hm3', name: 'Apollo Hospitals Enterprise', sector: 'Healthcare', allocationPct: 3.9, symbol: 'APOLLOHOSP' },
      { id: 'hm4', name: 'Federal Bank Ltd.', sector: 'Financial Services', allocationPct: 3.7, symbol: 'FEDERALBNK' },
      { id: 'hm5', name: 'Tata Communications Ltd.', sector: 'Telecommunication', allocationPct: 3.4, symbol: 'TATACOMM' },
      { id: 'hm6', name: 'Coforge Ltd.', sector: 'Information Technology', allocationPct: 3.1, symbol: 'COFORGE' },
      { id: 'hm7', name: 'Balkrishna Industries', sector: 'Automobile Ancillaries', allocationPct: 2.8, symbol: 'BALKRISIND' },
      { id: 'hm8', name: 'AU Small Finance Bank', sector: 'Financial Services', allocationPct: 2.6, symbol: 'AUBANK' },
    ],
    sectorAllocations: [
      { sector: 'Financial Services', allocationPct: 21.4, color: '#3B82F6' },
      { sector: 'Healthcare & Pharma', allocationPct: 16.8, color: '#10B981' },
      { sector: 'Consumer Services & Hotels', allocationPct: 14.2, color: '#F59E0B' },
      { sector: 'Industrial Manufacturing', allocationPct: 12.6, color: '#EC4899' },
      { sector: 'Information Technology', allocationPct: 11.5, color: '#8B5CF6' },
      { sector: 'Automobile Ancillaries', allocationPct: 8.9, color: '#6366F1' },
      { sector: 'Cash & Short Instruments', allocationPct: 14.6, color: '#94A3B8' },
    ],
    returnsComparison: [
      { period: '1M', fundReturn: 3.4, categoryAvg: 2.4, benchmarkReturn: 2.7 },
      { period: '6M', fundReturn: 14.8, categoryAvg: 11.6, benchmarkReturn: 12.5 },
      { period: '1Y', fundReturn: 34.2, categoryAvg: 28.4, benchmarkReturn: 29.8 },
      { period: '3Y', fundReturn: 26.5, categoryAvg: 21.8, benchmarkReturn: 22.4 },
      { period: '5Y', fundReturn: 23.8, categoryAvg: 18.5, benchmarkReturn: 19.2 },
      { period: 'Inception', fundReturn: 19.4, categoryAvg: 15.2, benchmarkReturn: 16.0 },
    ],
    navHistory: {
      '1M': [
        { date: '21 Aug', value: 176.4 },
        { date: '28 Aug', value: 177.8 },
        { date: '04 Sep', value: 179.1 },
        { date: '11 Sep', value: 180.5 },
        { date: '18 Sep', value: 181.2 },
        { date: '21 Sep', value: 182.35 },
      ],
      '6M': [
        { date: 'Mar 26', value: 158.8 },
        { date: 'Apr 26', value: 163.5 },
        { date: 'May 26', value: 161.2 },
        { date: 'Jun 26', value: 170.8 },
        { date: 'Jul 26', value: 175.4 },
        { date: 'Aug 26', value: 178.1 },
        { date: 'Sep 26', value: 182.35 },
      ],
      '1Y': [
        { date: 'Sep 25', value: 135.9 },
        { date: 'Nov 25', value: 144.2 },
        { date: 'Jan 26', value: 152.0 },
        { date: 'Mar 26', value: 158.8 },
        { date: 'May 26', value: 161.2 },
        { date: 'Jul 26', value: 175.4 },
        { date: 'Sep 26', value: 182.35 },
      ],
      '3Y': [
        { date: '2023', value: 89.6 },
        { date: '2024', value: 114.2 },
        { date: '2025', value: 145.0 },
        { date: '2026', value: 182.35 },
      ],
      '5Y': [
        { date: '2021', value: 62.8 },
        { date: '2022', value: 74.5 },
        { date: '2023', value: 89.6 },
        { date: '2024', value: 114.2 },
        { date: '2025', value: 145.0 },
        { date: '2026', value: 182.35 },
      ],
      'ALL': [
        { date: '2016', value: 38.5 },
        { date: '2018', value: 52.4 },
        { date: '2020', value: 49.8 },
        { date: '2022', value: 74.5 },
        { date: '2024', value: 114.2 },
        { date: '2026', value: 182.35 },
      ],
    },
  },
  {
    id: 'nippon-india-growth',
    name: 'Nippon India Growth Fund',
    amc: 'Nippon India Mutual Fund',
    amcCode: 'NIPPON',
    category: 'mid',
    categoryLabel: 'Mid Cap Fund',
    planType: 'Direct Plan - Growth',
    rating: 4,
    riskLevel: 'Very High',
    benchmark: 'NIFTY Midcap 150 TRI',
    currentNav: 3856.40,
    navChange: 42.10,
    navChangePct: 1.10,
    navDate: '21 Sep 2026',
    returns1M: 3.1,
    returns6M: 13.9,
    returns1Y: 32.5,
    returns3Y: 24.8,
    returns5Y: 22.4,
    returnsInception: 21.2,
    expenseRatio: 0.82,
    regularExpenseRatio: 1.69,
    aumCrores: 31200,
    minSipAmount: 500,
    minLumpsumAmount: 1000,
    exitLoad: '1.0% within 30 days; Nil after',
    lockInPeriod: 'None',
    turnoverRatioPct: 34.0,
    sharpeRatio: 1.35,
    beta: 0.94,
    manager: {
      name: 'Manish Gunwani',
      experienceYears: 24,
      tenureWithFund: '3.1 Years',
      education: 'B.Tech (IIT Madras), PGDM (IIM Bangalore)',
    },
    aiRecommendation: {
      isRecommended: true,
      matchScore: 91,
      badgeText: 'High Growth Compounder',
      rationale: 'Active stock picking focused on emerging market leaders with high return on capital.',
      pros: [
        'Short 30-day exit load window for flexibility',
        'Strong tilt towards domestic consumption and manufacturing beneficiaries',
      ],
      cons: [
        'Higher turnover ratio (34%) reflects tactical position rotations',
      ],
    },
    topHoldings: [
      { id: 'ng1', name: 'Power Finance Corp', sector: 'Financial Services', allocationPct: 4.2, symbol: 'PFC' },
      { id: 'ng2', name: 'Varun Beverages Ltd.', sector: 'FMCG', allocationPct: 3.9, symbol: 'VBL' },
      { id: 'ng3', name: 'Cholamandalam Investment', sector: 'Financial Services', allocationPct: 3.6, symbol: 'CHOLAFIN' },
      { id: 'ng4', name: 'Supreme Industries Ltd.', sector: 'Capital Goods', allocationPct: 3.2, symbol: 'SUPREMEIND' },
    ],
    sectorAllocations: [
      { sector: 'Financial Services', allocationPct: 24.5, color: '#3B82F6' },
      { sector: 'Capital Goods & Industrials', allocationPct: 18.2, color: '#EC4899' },
      { sector: 'Consumer Goods', allocationPct: 15.1, color: '#10B981' },
      { sector: 'Chemicals & Materials', allocationPct: 11.4, color: '#F59E0B' },
      { sector: 'Others & Cash', allocationPct: 30.8, color: '#94A3B8' },
    ],
    returnsComparison: [
      { period: '1M', fundReturn: 3.1, categoryAvg: 2.4, benchmarkReturn: 2.7 },
      { period: '6M', fundReturn: 13.9, categoryAvg: 11.6, benchmarkReturn: 12.5 },
      { period: '1Y', fundReturn: 32.5, categoryAvg: 28.4, benchmarkReturn: 29.8 },
      { period: '3Y', fundReturn: 24.8, categoryAvg: 21.8, benchmarkReturn: 22.4 },
      { period: '5Y', fundReturn: 22.4, categoryAvg: 18.5, benchmarkReturn: 19.2 },
      { period: 'Inception', fundReturn: 21.2, categoryAvg: 15.2, benchmarkReturn: 16.0 },
    ],
    navHistory: {
      '1M': [{ date: '21 Aug', value: 3740.2 }, { date: '21 Sep', value: 3856.40 }],
      '6M': [{ date: 'Mar 26', value: 3385.0 }, { date: 'Sep 26', value: 3856.40 }],
      '1Y': [{ date: 'Sep 25', value: 2910.0 }, { date: 'Sep 26', value: 3856.40 }],
      '3Y': [{ date: '2023', value: 1980.0 }, { date: '2026', value: 3856.40 }],
      '5Y': [{ date: '2021', value: 1380.0 }, { date: '2026', value: 3856.40 }],
      'ALL': [{ date: '2016', value: 820.0 }, { date: '2026', value: 3856.40 }],
    },
  },
  {
    id: 'kotak-emerging-equity',
    name: 'Kotak Emerging Equity Fund',
    amc: 'Kotak Mahindra Mutual Fund',
    amcCode: 'KOTAK',
    category: 'mid',
    categoryLabel: 'Mid Cap Fund',
    planType: 'Direct Plan - Growth',
    rating: 4,
    riskLevel: 'Very High',
    benchmark: 'NIFTY Midcap 150 TRI',
    currentNav: 124.50,
    navChange: 1.15,
    navChangePct: 0.93,
    navDate: '21 Sep 2026',
    returns1M: 2.8,
    returns6M: 12.8,
    returns1Y: 30.8,
    returns3Y: 23.9,
    returns5Y: 21.9,
    returnsInception: 18.8,
    expenseRatio: 0.78,
    regularExpenseRatio: 1.64,
    aumCrores: 45800,
    minSipAmount: 500,
    minLumpsumAmount: 1000,
    exitLoad: '1.0% within 365 days; Nil after',
    lockInPeriod: 'None',
    turnoverRatioPct: 24.5,
    sharpeRatio: 1.28,
    beta: 0.90,
    manager: {
      name: 'Pankaj Tibrewal',
      experienceYears: 20,
      tenureWithFund: '11.0 Years',
      education: 'B.Com, Master in Finance (Manchester)',
    },
    aiRecommendation: {
      isRecommended: true,
      matchScore: 93,
      badgeText: 'Proven Mid-Cap Veteran',
      rationale: 'Well-diversified portfolio with strict stop-loss and corporate governance thresholds.',
      pros: [
        'Over 11 years of steady performance under the same lead manager',
        'Strong track record in engineering, chemicals, and consumer themes',
      ],
      cons: [
        'Occasionally sits on 8-12% cash when valuations are stretched',
      ],
    },
    topHoldings: [
      { id: 'ke1', name: 'Persistent Systems Ltd.', sector: 'Technology', allocationPct: 4.5, symbol: 'PERSISTENT' },
      { id: 'ke2', name: 'Schaeffler India Ltd.', sector: 'Industrial Machinery', allocationPct: 4.1, symbol: 'SCHAEFFLER' },
      { id: 'ke3', name: 'Thermax Ltd.', sector: 'Capital Goods', allocationPct: 3.8, symbol: 'THERMAX' },
      { id: 'ke4', name: 'Supreme Industries Ltd.', sector: 'Consumer Goods', allocationPct: 3.5, symbol: 'SUPREMEIND' },
    ],
    sectorAllocations: [
      { sector: 'Industrial Goods & Mfg', allocationPct: 26.2, color: '#EC4899' },
      { sector: 'Financial Services', allocationPct: 18.5, color: '#3B82F6' },
      { sector: 'Information Technology', allocationPct: 14.1, color: '#8B5CF6' },
      { sector: 'Consumer Discretionary', allocationPct: 13.8, color: '#10B981' },
      { sector: 'Others & Cash', allocationPct: 27.4, color: '#94A3B8' },
    ],
    returnsComparison: [
      { period: '1M', fundReturn: 2.8, categoryAvg: 2.4, benchmarkReturn: 2.7 },
      { period: '6M', fundReturn: 12.8, categoryAvg: 11.6, benchmarkReturn: 12.5 },
      { period: '1Y', fundReturn: 30.8, categoryAvg: 28.4, benchmarkReturn: 29.8 },
      { period: '3Y', fundReturn: 23.9, categoryAvg: 21.8, benchmarkReturn: 22.4 },
      { period: '5Y', fundReturn: 21.9, categoryAvg: 18.5, benchmarkReturn: 19.2 },
      { period: 'Inception', fundReturn: 18.8, categoryAvg: 15.2, benchmarkReturn: 16.0 },
    ],
    navHistory: {
      '1M': [{ date: '21 Aug', value: 121.1 }, { date: '21 Sep', value: 124.50 }],
      '6M': [{ date: 'Mar 26', value: 110.3 }, { date: 'Sep 26', value: 124.50 }],
      '1Y': [{ date: 'Sep 25', value: 95.2 }, { date: 'Sep 26', value: 124.50 }],
      '3Y': [{ date: '2023', value: 65.5 }, { date: '2026', value: 124.50 }],
      '5Y': [{ date: '2021', value: 46.2 }, { date: '2026', value: 124.50 }],
      'ALL': [{ date: '2016', value: 24.1 }, { date: '2026', value: 124.50 }],
    },
  },

  // ==========================================
  // DEBT FUNDS
  // ==========================================
  {
    id: 'icici-pru-corporate-bond',
    name: 'ICICI Prudential Corporate Bond Fund',
    amc: 'ICICI Prudential Mutual Fund',
    amcCode: 'ICICI',
    category: 'debt',
    categoryLabel: 'Corporate Bond Fund (Debt)',
    planType: 'Direct Plan - Growth',
    rating: 5,
    riskLevel: 'Moderate',
    benchmark: 'CRISIL Composite Bond Fund Index',
    currentNav: 29.42,
    navChange: 0.02,
    navChangePct: 0.07,
    navDate: '21 Sep 2026',
    returns1M: 0.65,
    returns6M: 3.8,
    returns1Y: 7.95,
    returns3Y: 7.42,
    returns5Y: 7.28,
    returnsInception: 8.35,
    expenseRatio: 0.32,
    regularExpenseRatio: 0.61,
    aumCrores: 28600,
    minSipAmount: 500,
    minLumpsumAmount: 5000,
    exitLoad: 'Nil (0%)',
    lockInPeriod: 'None',
    turnoverRatioPct: 12.0,
    sharpeRatio: 1.85,
    beta: 0.15,
    manager: {
      name: 'Anuj Tagra',
      experienceYears: 16,
      tenureWithFund: '5.8 Years',
      education: 'B.Com, MBA (NMIMS)',
    },
    aiRecommendation: {
      isRecommended: true,
      matchScore: 95,
      badgeText: 'Top Safe Yield Pick 🛡️',
      rationale: '98%+ AAA-rated bonds and sovereign G-Secs with zero credit defaults in history.',
      pros: [
        'Zero exit load — withdraw anytime without penalty',
        '98.4% allocation to AAA and Sovereign instruments',
        'Rock-bottom 0.32% expense ratio preserves net yield',
      ],
      cons: [
        'Sensitive to RBI interest rate cycle movements',
      ],
    },
    topHoldings: [
      { id: 'd1', name: '7.18% Govt of India 2033 (G-Sec)', sector: 'Sovereign', allocationPct: 11.2, instrumentType: 'Govt Bond' },
      { id: 'd2', name: 'NABARD AAA Bond 2027', sector: 'Financial Institutions', allocationPct: 9.5, instrumentType: 'Debt' },
      { id: 'd3', name: 'HDFC Bank AAA 2028', sector: 'Banking', allocationPct: 8.8, instrumentType: 'Debt' },
      { id: 'd4', name: 'REC Ltd. AAA Bond 2027', sector: 'Power Finance', allocationPct: 8.1, instrumentType: 'Debt' },
      { id: 'd5', name: 'Power Finance Corp AAA', sector: 'Power Finance', allocationPct: 7.9, instrumentType: 'Debt' },
      { id: 'd6', name: 'Small Industries Dev Bank (SIDBI)', sector: 'Financial Institutions', allocationPct: 7.2, instrumentType: 'Debt' },
      { id: 'd7', name: 'Indian Railway Finance (IRFC)', sector: 'Railways Infrastructure', allocationPct: 6.8, instrumentType: 'Debt' },
      { id: 'd8', name: 'Treasury Bills (91 Days)', sector: 'Sovereign Short', allocationPct: 5.5, instrumentType: 'Govt Bond' },
    ],
    sectorAllocations: [
      { sector: 'AAA Corporate Bonds', allocationPct: 68.4, color: '#3B82F6' },
      { sector: 'Sovereign / G-Secs', allocationPct: 24.8, color: '#10B981' },
      { sector: 'Cash & Overnight Repos', allocationPct: 6.8, color: '#94A3B8' },
    ],
    returnsComparison: [
      { period: '1M', fundReturn: 0.65, categoryAvg: 0.58, benchmarkReturn: 0.60 },
      { period: '6M', fundReturn: 3.80, categoryAvg: 3.42, benchmarkReturn: 3.55 },
      { period: '1Y', fundReturn: 7.95, categoryAvg: 7.15, benchmarkReturn: 7.30 },
      { period: '3Y', fundReturn: 7.42, categoryAvg: 6.85, benchmarkReturn: 6.95 },
      { period: '5Y', fundReturn: 7.28, categoryAvg: 6.55, benchmarkReturn: 6.70 },
      { period: 'Inception', fundReturn: 8.35, categoryAvg: 7.40, benchmarkReturn: 7.60 },
    ],
    navHistory: {
      '1M': [
        { date: '21 Aug', value: 29.23 },
        { date: '28 Aug', value: 29.27 },
        { date: '04 Sep', value: 29.31 },
        { date: '11 Sep', value: 29.35 },
        { date: '18 Sep', value: 29.40 },
        { date: '21 Sep', value: 29.42 },
      ],
      '6M': [
        { date: 'Mar 26', value: 28.34 },
        { date: 'Apr 26', value: 28.51 },
        { date: 'May 26', value: 28.72 },
        { date: 'Jun 26', value: 28.94 },
        { date: 'Jul 26', value: 29.12 },
        { date: 'Aug 26', value: 29.28 },
        { date: 'Sep 26', value: 29.42 },
      ],
      '1Y': [
        { date: 'Sep 25', value: 27.25 },
        { date: 'Nov 25', value: 27.60 },
        { date: 'Jan 26', value: 28.02 },
        { date: 'Mar 26', value: 28.34 },
        { date: 'May 26', value: 28.72 },
        { date: 'Jul 26', value: 29.12 },
        { date: 'Sep 26', value: 29.42 },
      ],
      '3Y': [
        { date: '2023', value: 23.75 },
        { date: '2024', value: 25.48 },
        { date: '2025', value: 27.25 },
        { date: '2026', value: 29.42 },
      ],
      '5Y': [
        { date: '2021', value: 20.72 },
        { date: '2022', value: 22.10 },
        { date: '2023', value: 23.75 },
        { date: '2024', value: 25.48 },
        { date: '2025', value: 27.25 },
        { date: '2026', value: 29.42 },
      ],
      'ALL': [
        { date: '2016', value: 14.80 },
        { date: '2018', value: 17.20 },
        { date: '2020', value: 19.40 },
        { date: '2022', value: 22.10 },
        { date: '2024', value: 25.48 },
        { date: '2026', value: 29.42 },
      ],
    },
  },
  {
    id: 'hdfc-short-term-debt',
    name: 'HDFC Short Term Debt Fund',
    amc: 'HDFC Mutual Fund',
    amcCode: 'HDFC',
    category: 'debt',
    categoryLabel: 'Short Duration Fund (Debt)',
    planType: 'Direct Plan - Growth',
    rating: 4,
    riskLevel: 'Moderate',
    benchmark: 'CRISIL Short Duration Debt Index',
    currentNav: 31.85,
    navChange: 0.02,
    navChangePct: 0.06,
    navDate: '21 Sep 2026',
    returns1M: 0.62,
    returns6M: 3.72,
    returns1Y: 7.82,
    returns3Y: 7.25,
    returns5Y: 7.10,
    returnsInception: 8.12,
    expenseRatio: 0.35,
    regularExpenseRatio: 0.72,
    aumCrores: 19800,
    minSipAmount: 500,
    minLumpsumAmount: 5000,
    exitLoad: 'Nil (0%)',
    lockInPeriod: 'None',
    turnoverRatioPct: 18.0,
    sharpeRatio: 1.76,
    beta: 0.12,
    manager: {
      name: 'Anil Bamboli',
      experienceYears: 24,
      tenureWithFund: '8.2 Years',
      education: 'B.Com, MMS (Finance)',
    },
    aiRecommendation: {
      isRecommended: false,
      matchScore: 88,
      badgeText: 'Short Duration Stability',
      rationale: 'High portfolio liquidity matching 1-3 year horizon with low duration risk.',
      pros: [
        'Ideal parking solution for 1 to 3 year money',
        'Minimal interest rate duration fluctuations',
      ],
      cons: [
        'Yield capped during sharp interest rate cuts',
      ],
    },
    topHoldings: [
      { id: 'hd1', name: '7.06% Govt of India 2028', sector: 'Sovereign', allocationPct: 12.5, instrumentType: 'Govt Bond' },
      { id: 'hd2', name: 'HDFC Bank Ltd. AAA', sector: 'Banking', allocationPct: 9.8, instrumentType: 'Debt' },
      { id: 'hd3', name: 'NABARD AAA 2027', sector: 'Financial Institutions', allocationPct: 8.4, instrumentType: 'Debt' },
    ],
    sectorAllocations: [
      { sector: 'AAA Corporate Debt', allocationPct: 62.5, color: '#3B82F6' },
      { sector: 'Sovereign G-Secs', allocationPct: 30.2, color: '#10B981' },
      { sector: 'Cash & Short Repo', allocationPct: 7.3, color: '#94A3B8' },
    ],
    returnsComparison: [
      { period: '1M', fundReturn: 0.62, categoryAvg: 0.58, benchmarkReturn: 0.60 },
      { period: '6M', fundReturn: 3.72, categoryAvg: 3.42, benchmarkReturn: 3.55 },
      { period: '1Y', fundReturn: 7.82, categoryAvg: 7.15, benchmarkReturn: 7.30 },
      { period: '3Y', fundReturn: 7.25, categoryAvg: 6.85, benchmarkReturn: 6.95 },
      { period: '5Y', fundReturn: 7.10, categoryAvg: 6.55, benchmarkReturn: 6.70 },
      { period: 'Inception', fundReturn: 8.12, categoryAvg: 7.40, benchmarkReturn: 7.60 },
    ],
    navHistory: {
      '1M': [{ date: '21 Aug', value: 31.65 }, { date: '21 Sep', value: 31.85 }],
      '6M': [{ date: 'Mar 26', value: 30.70 }, { date: 'Sep 26', value: 31.85 }],
      '1Y': [{ date: 'Sep 25', value: 29.54 }, { date: 'Sep 26', value: 31.85 }],
      '3Y': [{ date: '2023', value: 25.80 }, { date: '2026', value: 31.85 }],
      '5Y': [{ date: '2021', value: 22.60 }, { date: '2026', value: 31.85 }],
      'ALL': [{ date: '2016', value: 16.20 }, { date: '2026', value: 31.85 }],
    },
  },
  {
    id: 'sbi-magnum-gilt',
    name: 'SBI Magnum Gilt Fund',
    amc: 'SBI Mutual Fund',
    amcCode: 'SBI',
    category: 'debt',
    categoryLabel: 'Gilt Fund (100% Govt Securities)',
    planType: 'Direct Plan - Growth',
    rating: 4,
    riskLevel: 'Moderate',
    benchmark: 'CRISIL Dynamic Gilt Index',
    currentNav: 62.48,
    navChange: 0.05,
    navChangePct: 0.08,
    navDate: '21 Sep 2026',
    returns1M: 0.72,
    returns6M: 4.15,
    returns1Y: 8.65,
    returns3Y: 7.85,
    returns5Y: 7.65,
    returnsInception: 8.75,
    expenseRatio: 0.44,
    regularExpenseRatio: 0.95,
    aumCrores: 12400,
    minSipAmount: 500,
    minLumpsumAmount: 5000,
    exitLoad: 'Nil (0%)',
    lockInPeriod: 'None',
    turnoverRatioPct: 42.0,
    sharpeRatio: 1.68,
    beta: 0.28,
    manager: {
      name: 'Dinesh Ahuja',
      experienceYears: 23,
      tenureWithFund: '12.0 Years',
      education: 'B.Com, MMS (Finance)',
    },
    aiRecommendation: {
      isRecommended: true,
      matchScore: 92,
      badgeText: 'Zero Credit Risk 🏛️',
      rationale: 'Backed 100% by the Government of India. Absolute zero default risk with duration gains during rate cuts.',
      pros: [
        'Zero credit risk — sovereign guarantee of Government of India',
        'High capital gains during interest rate falling cycles',
      ],
      cons: [
        'Longer maturity instruments can fluctuate when bond yields rise',
      ],
    },
    topHoldings: [
      { id: 'sg1', name: '7.26% GOI 2033 (10-Yr Benchmark)', sector: 'Sovereign', allocationPct: 34.2, instrumentType: 'Govt Bond' },
      { id: 'sg2', name: '7.18% GOI 2037', sector: 'Sovereign', allocationPct: 28.5, instrumentType: 'Govt Bond' },
      { id: 'sg3', name: 'State Development Loan (SDL) Gujarat', sector: 'Sovereign State', allocationPct: 18.2, instrumentType: 'Govt Bond' },
      { id: 'sg4', name: '182-Day Treasury Bills', sector: 'Sovereign Short', allocationPct: 11.5, instrumentType: 'Govt Bond' },
    ],
    sectorAllocations: [
      { sector: 'Central Government G-Secs', allocationPct: 68.2, color: '#10B981' },
      { sector: 'State Development Loans (SDL)', allocationPct: 22.4, color: '#3B82F6' },
      { sector: 'Cash & Repos', allocationPct: 9.4, color: '#94A3B8' },
    ],
    returnsComparison: [
      { period: '1M', fundReturn: 0.72, categoryAvg: 0.58, benchmarkReturn: 0.60 },
      { period: '6M', fundReturn: 4.15, categoryAvg: 3.42, benchmarkReturn: 3.55 },
      { period: '1Y', fundReturn: 8.65, categoryAvg: 7.15, benchmarkReturn: 7.30 },
      { period: '3Y', fundReturn: 7.85, categoryAvg: 6.85, benchmarkReturn: 6.95 },
      { period: '5Y', fundReturn: 7.65, categoryAvg: 6.55, benchmarkReturn: 6.70 },
      { period: 'Inception', fundReturn: 8.75, categoryAvg: 7.40, benchmarkReturn: 7.60 },
    ],
    navHistory: {
      '1M': [{ date: '21 Aug', value: 62.03 }, { date: '21 Sep', value: 62.48 }],
      '6M': [{ date: 'Mar 26', value: 59.98 }, { date: 'Sep 26', value: 62.48 }],
      '1Y': [{ date: 'Sep 25', value: 57.50 }, { date: 'Sep 26', value: 62.48 }],
      '3Y': [{ date: '2023', value: 49.80 }, { date: '2026', value: 62.48 }],
      '5Y': [{ date: '2021', value: 43.20 }, { date: '2026', value: 62.48 }],
      'ALL': [{ date: '2016', value: 29.50 }, { date: '2026', value: 62.48 }],
    },
  },
];
