import { FinancialGoal, MutualFundInfo, SIPPlan } from './sip.types';

export const TOP_MUTUAL_FUNDS: MutualFundInfo[] = [
  {
    id: 'mf-ppfas-flexi',
    name: 'Parag Parikh Flexi Cap Fund',
    amc: 'PPFAS Mutual Fund',
    category: 'Flexi Cap',
    nav: 84.72,
    navDate: 'Today',
    cagr3Y: 19.8,
    cagr5Y: 22.4,
    minSip: 1000,
    rating: 5,
    aum: '₹64,120 Cr',
    expenseRatio: 0.63,
    risk: 'Very High',
    icon: '🛡️',
  },
  {
    id: 'mf-mirae-large',
    name: 'Mirae Asset Large Cap Fund',
    amc: 'Mirae Asset Mutual Fund',
    category: 'Large Cap',
    nav: 112.45,
    navDate: 'Today',
    cagr3Y: 15.2,
    cagr5Y: 16.8,
    minSip: 500,
    rating: 4,
    aum: '₹37,840 Cr',
    expenseRatio: 0.54,
    risk: 'High',
    icon: '🏛️',
  },
  {
    id: 'mf-hdfc-midcap',
    name: 'HDFC Mid-Cap Opportunities Fund',
    amc: 'HDFC Mutual Fund',
    category: 'Mid Cap',
    nav: 184.20,
    navDate: 'Today',
    cagr3Y: 24.6,
    cagr5Y: 23.1,
    minSip: 500,
    rating: 5,
    aum: '₹58,900 Cr',
    expenseRatio: 0.72,
    risk: 'Very High',
    icon: '🚀',
  },
  {
    id: 'mf-sbi-small',
    name: 'SBI Small Cap Fund Direct-Growth',
    amc: 'SBI Mutual Fund',
    category: 'Small Cap',
    nav: 164.80,
    navDate: 'Today',
    cagr3Y: 22.3,
    cagr5Y: 24.5,
    minSip: 500,
    rating: 4,
    aum: '₹26,400 Cr',
    expenseRatio: 0.68,
    risk: 'Very High',
    icon: '⚡',
  },
  {
    id: 'mf-bandhan-liquid',
    name: 'Bandhan Liquid Fund Direct-Growth',
    amc: 'Bandhan Mutual Fund',
    category: 'Debt & Liquid',
    nav: 29.35,
    navDate: 'Today',
    cagr3Y: 6.8,
    cagr5Y: 6.2,
    minSip: 1000,
    rating: 4,
    aum: '₹14,200 Cr',
    expenseRatio: 0.18,
    risk: 'Low',
    icon: '💧',
  },
  {
    id: 'mf-quant-elss',
    name: 'Quant ELSS Tax Saver Fund',
    amc: 'Quant Mutual Fund',
    category: 'ELSS Tax Saver',
    nav: 382.10,
    navDate: 'Today',
    cagr3Y: 26.4,
    cagr5Y: 28.2,
    minSip: 500,
    rating: 5,
    aum: '₹9,850 Cr',
    expenseRatio: 0.77,
    risk: 'Very High',
    icon: '🧾',
  },
];

export const INITIAL_GOALS: FinancialGoal[] = [
  {
    id: 'goal-house',
    title: 'Down Payment for Dream Flat',
    emoji: '🏠',
    category: 'House',
    targetAmount: 2500000, // ₹25 Lakhs
    currentAmount: 840000,  // ₹8.4 Lakhs
    targetDate: '2028-12',  // Dec 2028
    createdDate: '2023-01-15',
    priority: 'High',
    expectedReturnRate: 13,
    linkedSipIds: ['sip-1', 'sip-2'],
  },
  {
    id: 'goal-car',
    title: 'Electric SUV Purchase',
    emoji: '🚗',
    category: 'Car',
    targetAmount: 1200000, // ₹12 Lakhs
    currentAmount: 620000,  // ₹6.2 Lakhs
    targetDate: '2026-10',  // Oct 2026
    createdDate: '2023-06-01',
    priority: 'Medium',
    expectedReturnRate: 12,
    linkedSipIds: ['sip-3'],
  },
  {
    id: 'goal-emergency',
    title: '6-Month Emergency Buffer',
    emoji: '🛡️',
    category: 'Emergency',
    targetAmount: 400000,  // ₹4 Lakhs
    currentAmount: 360000,  // ₹3.6 Lakhs
    targetDate: '2025-06',  // Jun 2025
    createdDate: '2023-01-01',
    priority: 'High',
    expectedReturnRate: 7,
    linkedSipIds: [],
  },
];

export const INITIAL_SIPS: SIPPlan[] = [
  {
    id: 'sip-1',
    clientSipId: 'SIP-PPFAS-98124',
    fundId: 'mf-ppfas-flexi',
    fundName: 'Parag Parikh Flexi Cap Fund',
    amc: 'PPFAS Mutual Fund',
    category: 'Flexi Cap',
    amount: 5000,
    frequency: 'monthly',
    debitDay: 5,
    startDate: '2023-02-05',
    nextDebitDate: '05 Oct 2026',
    status: 'ACTIVE',
    goalId: 'goal-house',
    goalTitle: 'Down Payment for Dream Flat',
    mandateUrn: 'UMRN/HDFC/2023/8892182',
    bankName: 'HDFC Bank',
    accountLast4: '4821',
    upiApp: 'Google Pay',
    upiId: 'user@okhdfcbank',
    totalInstallmentsPaid: 20,
    totalInvested: 100000,
  },
  {
    id: 'sip-2',
    clientSipId: 'SIP-HDFC-33921',
    fundId: 'mf-hdfc-midcap',
    fundName: 'HDFC Mid-Cap Opportunities Fund',
    amc: 'HDFC Mutual Fund',
    category: 'Mid Cap',
    amount: 3500,
    frequency: 'monthly',
    debitDay: 10,
    startDate: '2023-03-10',
    nextDebitDate: '10 Oct 2026',
    status: 'ACTIVE',
    goalId: 'goal-house',
    goalTitle: 'Down Payment for Dream Flat',
    mandateUrn: 'UMRN/HDFC/2023/4491021',
    bankName: 'HDFC Bank',
    accountLast4: '4821',
    upiApp: 'PhonePe',
    upiId: 'user@ybl',
    totalInstallmentsPaid: 19,
    totalInvested: 66500,
  },
  {
    id: 'sip-3',
    clientSipId: 'SIP-MIRAE-77120',
    fundId: 'mf-mirae-large',
    fundName: 'Mirae Asset Large Cap Fund',
    amc: 'Mirae Asset Mutual Fund',
    category: 'Large Cap',
    amount: 4000,
    frequency: 'monthly',
    debitDay: 15,
    startDate: '2023-06-15',
    nextDebitDate: '15 Oct 2026',
    status: 'ACTIVE',
    goalId: 'goal-car',
    goalTitle: 'Electric SUV Purchase',
    mandateUrn: 'UMRN/ICICI/2023/1109482',
    bankName: 'ICICI Bank',
    accountLast4: '9924',
    upiApp: 'Paytm UPI',
    upiId: 'user@paytm',
    totalInstallmentsPaid: 15,
    totalInvested: 60000,
  },
];
